### ISSUE TITLE
[feature?] Request to allow bees to enter locked hives and nests

### ISSUE THREAD

**Issue by mrfloris** [pop4959/Bolt#153]
From what I observe, when we have it to auto lock hives and nests (which yes, we want, sorry) then bees can't interact with it either. So that's not what players want, and they end up /unlocking, and others then ruin the fun by breaking and stealing them. Because fancy item stuff. 

```yaml
  bee_nest:
    autoProtect: private
    autoProtectPermission: true
  beehive:
    autoProtect: private
    autoProtectPermission: true
```

Is it possible to use public or deposit or some setting to get it to remain locked (unable to break) but public enough that bees can interact? Maybe an exception can be made for this situation as we can assume players want bees to enter it most of the time?

Not sure about edge case situations where ppl use it to make builds, etc. but .. worth thinking about perhaps?
