### ISSUE TITLE
[Feature] Setting for door sound volume

### ISSUE THREAD

**Issue by RHX0R3** [pop4959/Bolt#195]
Hey pop,

as for the open-double and open-iron features, the sounds for opening and closing doors and trapdoors are loud.
I assume, that you set the volume to 1.0f.

Would you consider adding an option to the config file for setting the volume?
The doors section then could look like this:

```
doors:
  open-iron: false
  open-double: false
  close-after: 3
  action-volume: 1.0f  # Choose a value between 0.0f and 1.0f. Default is 1.0f.
```

Thank you for reading!

Best regards,
X0R3
