### ISSUE TITLE
Permission option for specific block/entity protection(s)

### ISSUE THREAD

**Issue by MC-MrBirdy** [pop4959/Bolt#62]
A suggestion for a feature to add the option to configure permissions for specific blocks/entities to only allow protecting them when having said permission.

For example:
```
blocks:
  chest:
    autoProtect: private
  lever:
    autoProtect: false
    permission: bolt.block.moderator
  stone_button:
    autoProtect: false
    permission: bolt.block.moderator
  spawner:
    autoProtect: false
    permission: bolt.block.admin
```

That way the permission "bolt.block.moderator" or "bolt.block.admin" can be given to specific players/groups.
Allowing for example only moderators to protect a lever and stone_button.

When no permission is specified all players can use it, which would be the default.

Being able to define the permission name can allow for multiple blocks/entities being covered by the same permission.
